---
- hosts: leaf1-DC1
  gather_facts: no
  tasks:
  - name: Create template
    template:
      src: "{{lookup('env','PWD')}}/templates/vlans.j2"
      dest: "{{lookup('env','PWD')}}/configs/vlans.cfg"
  -name: upload configs
    arista.eos.eos_config:
      src: "{{lookup('evn',PWD)}}/configs/vlans.cfg"