---
- hosts: all
  gather_facts: no
  tasks:
  - name: Create template
    template:
      src: "{{lookup('env','PWD')}}/templates/no_vlans.j2"
      dest: "{{lookup('env','PWD')}}/configs/no_{{inventory_hostname}}_vlans.cfg"
  - name: upload configs
    arista.eos.eos_config:
      src: "{{lookup('env','PWD')}}/configs/no_{{inventory_hostname}}_vlans.cfg"