---
- name: Download ATD-INFRA configlet
  hosts: CloudVision
  connection: local
  vars: 
    path: "{{lookup('env','PWD')}}"
  vars_files: 
     - ../vars/CVP_model.yml
  tasks:
    - name: Register variables (underlay)
      include_vars:
        file: "{{lookup('env','PWD')}}/vars/underlay.yml"
        name: underlay
    - name: Generate Var data structure
      template: 
        src: "{{lookup('env','PWD')}}/templates/CVP_model.j2"
        dest: "{{lookup('env','PWD')}}/vars/CVP_model.yml"

    # - name: Upload Configlets for OSPF Underlay
    #   arista.cvp.cv_configlet_v3:
    #     configlets: "{{ CVP_CONFIGLETS_EVPN }}"
    #     state: present 